server:
  port: 8222

eureka:
  client:
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: products-route
          uri: http://localhost:8080
          predicates:
            - Path=/products/**

        - id: orders-route
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**

        - id: carts-route
          uri: http://localhost:8082
          predicates:
            - Path=/carts/**